name: SytooxOnlyUp
version: '1.0.0'
main: net.sytoox.OnlyUp
api-version: '1.20'


commands:
  onlyup-finish:
    description: Only Up Ende Teleport Command
    aliases:

  onlyup-start:
    description: OnlyUp Start Teleport Command
    aliases:
